version: '3'
# Health checks?
services:
  registry:
    image: jgoyette/registry
    build: ./registry
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  gateway:
    image: jgoyette/gateway
    build: ./gateway
    ports:
      - "8762:8762"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8762/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  app1:
    image: jgoyette/app1
    build: ./app1
    #    environment:
    #      - SPRING_PROFILES_ACTIVE=noServiceDiscovery
    ports:
      - "8110:8110"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8110/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  app2:
    image: jgoyette/app2
    build: ./app2
    depends_on:
      - postgres
      - keycloak
        #    environment:
        #- SPRING_PROFILES_ACTIVE=noServiceDiscovery
    ports:
      - "8111:8111"
      - "8112:8112"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8111/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  postgres:
    image: postgres
    volumes:
      - /Users/jgoye/postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U spring_poc"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=spring_poc
      - POSTGRES_USER=spring_poc
      - POSTGRES_PASSWORD=poc_admin
  keycloak:
    image: jboss/keycloak
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    depends_on:
      - postgres
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=spring_poc
      - DB_USER=spring_poc
      - DB_PASSWORD=poc_admin
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
