server:
  port: 8110


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://registry:8761/eureka
spring:
  application:
    name: app1

apiHost: app2

---

spring:
  profiles: noServiceDiscovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

apiHost: app2:8111

---

spring:
  profiles: local

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka