keycloak-client:
  server-url: http://keycloak:8080/auth
  realm: test
  registration-id: my-keycloak

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
          jwt:
            jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
      client:
        registration:
          my-keycloak:
            client-id: gateway
            client-secret: fa6d64f0-246d-431b-90db-30c1fd3acd13
            provider: keycloak
            scope: openid, profile
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            token-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/token
            authorization-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/auth
            user-info-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
            user-name-attribute: preferred_username
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 8762
  servlet:
    context-path:
  error:
    include-stacktrace: always
eureka:
  client:
    service-url:
      defaultZone: http://registry:8761/eureka
    enabled: true
  instance:
    prefer-ip-address: true

#logging:
#  level:
#    org:
#      springframework: TRACE

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway